services:
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ycsb/init_postgres.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  scylla:
    image: scylladb/scylla
    command: []
    ports:
      - "9042:9042"
    volumes:
      - scylladata:/var/lib/scylla
    networks:
      - default

volumes:
  pgdata: {}
  scylladata: {}

networks:
  default:
    driver: bridge
